one = es_tests_more_norm[c(1,2,3,4,5,6)]
boxplot(one, main="Precision at 10 of different normalisation actions")
mean_d = mean(one$d)
points(1:1, mean_d)
mean_j = mean(one$j)
points(2:2, mean_j)
mean_k = mean(one$k)
points(3:3, mean_k)
mean_p = mean(one$p)
points(4:4, mean_p)
mean_s = mean(one$p)
mean_s = mean(one$s)
points(5:5, mean_s)
mean_w = mean(one$w)
points(6:6, mean_w)
