es_tests_decompiled <- read.csv("~/Documents/es_exp/analysis/es_tests_decompiled.csv")
View(es_tests_decompiled)
boxplot(es_tests_decompiled)
boxplot(es_tests_decompiled, ylim = c(0.4:1.0))
boxplot(es_tests_decompiled, pars=list(ylim=c(0.4,1.0)))
boxplot(es_tests_decompiled, pars=list(ylim=c(0.8,1.0)))
boxplot(es_tests_decompiled)
mean_orig = mean(es_tests_decompiled$Original)
points(1:1, mean_orig)
points(1:1, mean_orig, col="red")
mean_k = mean(es_tests_decompiled$Krakatau)
points(2:2, mean_k, col="red")
mean_k2 = mean(es_tests_decompiled$K.WJK)
points(3:3, mean_k2, col="red")
mean_k3 = mean(es_tests_decompiled$K.WJK.ngram)
points(4:4, mean_k3, col="red")
mean_p = mean(es_tests_decompiled$Procyon)
points(5:5, mean_p, col="red")
mean_p2 = mean(es_tests_decompiled$P.WJK)
points(6:6, mean_p2, col="red")
mean_p3 = mean(es_tests_decompiled$P.WJK.ngram)
points(7:7, mean_p3, col="red")
title("Precision at 10 before/after comp/decompilation")
